export const GETTING_TIME = 'GETTING_TIME';
export const GETTING_FAILED = 'GETTING_FAILED';

export const ERROR_STATUS_ADDED = 'ERROR_STATUS_ADDED';
export const SUCCESS_STATUS_ADDED = 'SUCCESS_STATUS_ADDED';
export const STATUS_CLEARED = 'STATUS_CLEARED';

export const PROFILE_GOT = 'PROFILE_GOT';
export const TASKS_GOT = 'TASKS_GOT';
export const SIGNIN_SUCCESS = 'SIGNIN_SUCCESS';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
